import { ThemeProvider } from "@/theme";
import { ColorSchemeScript } from "@mantine/core";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";
import "./global.css";
import { Notifications } from "@mantine/notifications";
import { Locale } from "../../i18n-config";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<
  {
    children: React.ReactNode;
  } & {
    params: { lang: Locale };
  }
>) {
  return (
    <html lang={params.lang}>
      <head>
        <ColorSchemeScript defaultColorScheme="auto" />
      </head>
      <body className={inter.className}>
        <ThemeProvider>
          {children}
          <Notifications position="bottom-center" />
        </ThemeProvider>
      </body>
    </html>
  );
}
