import { ThemeProvider } from "@/theme";
import { Footer } from "@/components/layout/Footer";
import { Header } from "@/components/layout/Header";
import { ColorSchemeScript } from "@mantine/core";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";
import "./global.css";
import { Notifications } from "@mantine/notifications";
import { Locale } from "../../i18n-config";
import { getGlobalPageData } from "@/data/loaders";
import { getUserMeLoader } from "@/data/services/get-user-me-loader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<
  {
    children: React.ReactNode;
  } & {
    params: { lang: Locale };
  }
>) {
  const globalData = await getGlobalPageData();
  const user = await getUserMeLoader();

  return (
    <html lang={params.lang}>
      <head>
        <ColorSchemeScript defaultColorScheme="auto" />
      </head>
      <body className={inter.className}>
        <ThemeProvider>
          <div className="relative flex flex-col min-h-screen">
            <Header {...globalData.attributes.header} user={user} />
            <main className="flex-1">{children}</main>
            <Footer {...globalData.attributes.footer} />
          </div>
          <Notifications position="bottom-center" />
        </ThemeProvider>
      </body>
    </html>
  );
}
