import { ThemeProvider } from "@/theme";
import "@mantine/core/styles.css";
import "../global.css";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
// import { Locale } from "../../../i18n-config";
import { ColorSchemeScript } from "@mantine/core";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  props: any,
  // : Readonly<
  //   {
  //     children: React.ReactNode;
  //   } & {
  //     params: { lang: Locale };
  //   }
  // >,
) {
  const params = await props.params;

  const { children } = props;

  return (
    <html lang={params.lang}>
      <head>
        <ColorSchemeScript defaultColorScheme="auto" />
      </head>
      <body
        className={cn(
          inter.className,
          "h-screen",
          "flex justify-center items-center",
        )}
      >
        <ThemeProvider>
          <main className="m-auto">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
